==================
FriCAS ECL Library
==================

Create ``libfricas.fas`` from an official source tarball.

Requirements
------------

 * ``make, tar``
 * ``curl`` or ``wget``
 * ``ECL`` (version ``16.+`` recommended)
 
Build
-----

The quickest method::
    
    git clone ...
    cd 
    make all
    
There are, however, a lot of targets in ``Makefile`` allowing
to perform almost each step separately::
    
    # Targets:
    # -- make .download ................... Download latest source tarball
    # -- make .unpack ..................... Extract to fricas-x.y.z in CWD
    # -- make .credirs .................... Creates build directories
    # -- make .interp ..................... Run configure & make. Builds interp
    # -- make .algebra .................... interp + compile the algebra
    # -- make .faslib ..................... Create libfricas.fas (interp)
    # -- make .copyfiles .................. Copy files to build directories
    # -- make precheck .................... Default. Do some pre-checking.
    # -- make test ........................ Should startup FriCAS Interpreter
    # -- make clean ....................... Perform some tidiying (partial clean)
    # -- make install ..................... Install to /usr/local/lib/ ? NYI
    # -- make lib ......................... .credirs/.algebra/.faslib/.copyfiles
    # -- make all ......................... .download/.unpack/lib
    #

.. tip::

    ``make`` without arguments performs some pre-checking (same 
    as ``make precheck``). 
    
In case you do not like automated download/extraction then you have to do it 
manually (``make precheck`` will show an url). Extract the 
source tarball into the folder where the ``Makefile`` is, then do:

 1. ``make precheck`` (optional)
 2. ``make lib``
 3. ``make test`` (optional)
  


